services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: laurus-777-db
    volumes:
      - ${DB_PATH_VOLUME}:/var/lib/postgresql/data
